.TH YAGTD 1 2008-11-30 "" COMMANDS

.SH NAME
yagtd \- utility to help organize your to-do lists

.SH SYNOPSIS
.B yagtd
[options] 
.I <file>

.SH DESCRIPTION
.\".B yagtd
.\"is based on the 
.\".I Getting Things Done 
.\"(GTD) method of time management developed by David Allen. 
.\".P
.B yagtd
is invoked with the name of a text file as first and
only argument. This file is used to store the to-do list. 
.P
.B yagtd 
opens an interactive command-prompt for adding,
managing and viewing to-do items.
.P
The command mode is described in the 
.I yagtd manual.
The manual also includes a practical introduction to using yagtd.

.SH OPTIONS
.IP "\fB\-c, --color"
Activate color highlighting

.IP "\fB\-q, --quiet"
Do not print copyright message

.SH SEE ALSO
.P
The yagtd manual. Installed on Debian systems in
/usr/share/doc/yagtd/rest/yagtd.html. Can also be found
online on the yagtd website.
.P
Website - https://gna.org/projects/yagtd/
